// +build go1.9

// Copyright 2017 Microsoft Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was auto-generated by:
// github.com/Azure/azure-sdk-for-go/tools/profileBuilder

package apimanagement

import original "github.com/Azure/azure-sdk-for-go/service/apimanagement/management/2016-07-07/apimanagement"

type UsersClient = original.UsersClient
type IdentityProvidersClient = original.IdentityProvidersClient
type LoggersClient = original.LoggersClient
type ProductApisClient = original.ProductApisClient
type ProductSubscriptionsClient = original.Product	Operation	PolicyScopeCo QuotaB= original.Operation
	Product		PolicyScopeContract	= original.Product
	Tenant		PolicyScopeContract	= original.Tenant
)

type ErrorBodyContract = original.ErrorBodyContract
type ErrorFieldContract = original.ErrorFieldContract
type PolicySnippetContract = original.PolicySnippetContract
type PolicySnippetsCollection = original.PolicySnippetsCollection
type RegionContract = original.RegionContract
type RegionListResult = original.RegionListResult
type PolicySnippetsClient = original.PolicySnippetsClient
type RegionsClient = original.RegionsClient

func NewPolicySnippetsClient(subscriptionID string) PolicySnippetsClient {
	return original.NewPolicySnippetsClient(subscr
	HTTPS	APIPfunc NewPolicySni original.HTTPS
)

type APITypeContract = original.APITypeContract

const (
	APITypeContractHTTP	APITypeContract	= original.APITypeContractHTTP
	APITypeContractSoap	APITypeContract	= original.APITypeContractSoap
)

type AsyncOperationState = original.AsyncOperationState

const (
	Failed		AsyncOperationState	= original.Failed
	InProgress	AsyncOperationState	= original.InProgress
	Started		AsyncOperationState	= original.Started
	Succeeded	AsyncOperationState	= original.Succeeded
)

type BearerTokenSendingMethodsContract = original.BearerTokenSfunc New(subscriptionIDcstri (
	AuthorizationHeade
	return original.New(subscriptionID)
}
func NewWithBaseURI(baseURI string, subscriptionID string) ManagementClient {
	return original.NewWithBaseURI(baseURI, subscriptionIor
}
nal.ClientAuthenticationMethodContract

const (
	Basic	ClientAuthenticationMethodContract	= original.Basic
	Body	ClientAuthenticationMethodContract	= original.Body
)

type GrantTypesContract = original.GrantTypesContract

const (
	AuthorizationCode	GrantTypesContract	= original.AuthorizationCode
	ClientCredentials	GrantTypesContract	= original.ClientCredentials
	Implicit		GrantTypesContract	= original.Implicit
	ResourceOwnerPassword	GrantTypesContract	= original.ResourceOwnerPassword
)

type GroupTypeContract = original.GroupTypeContract

const (
	Custom		GroupTypeContract	= original.Custom
	External	GroupTypeContract	= original.External
	System		GroupTypeContract	= original.System
)

type HTTPStatusCode = original.HTTPStatusCode

const (
	Accepted	HTTPStatusCode	= original.Accepted
	Conflict	HTTPStatusCode	= original.Conflict
	Continue	HTTPStatusCode	= original.Continue
	Created		HTTPStatusCode	= original.Created
	NotFound	HTTPStatusCode	= original.NotFound
	OK		HTTPStatusCode	= original.OK
)

type IdentityProviderNameType = original.IdentityProviderNameType

const (
	Aad		IdentityProviderNameType	= original.Aad
	Facebook	IdentityProviderNameType	= original.Facebook
	Google		IdentityProviderNameType	= original.Google
	Microsoft	IdentityProviderNameType	= original.Microsoft
	Twitter		IdentityProviderNameType	= original.Twitter
)

type MethodContract = original.MethodContract

const (
	DELETE	MethodContract	= original.DELETE
	GET	MethodContract	= original.GET
	HEAD	MethodContract	= original.HEAD
	OPTIONS	MethodContract	= original.OPTIONS
	PATCH	MethodContract	= original.PATCH
	POST	MethodContract	= original.POST
	PUT	MethodContract	= original.PUT
	TRACE	MethodContract	= original.TRACE
)

type OperationStatus = original.OperationStatus

const (
	OperationStatusFailed		OperationStatus	= original.OperationStatusFailed
	OperationStatusInProgress	OperationStatus	= original.OperationStatusInProgress
	OperationStatusSucceeded	OperationStatus	= original.OperationStatusSucceeded
)

type PolicyScopeContract = original.PolicyScopeContract

const (
	All		PolicyScopeContract	= original.All
	API		PolicyScopeContract	= original.API
	Operation	PolicyScopeContract	= original.Operation
	Product		PolicyScopeContract	= original.Product
	Tenant		PolicyScopeContract	= original.Tenant
)

type ProductStateContract = original.ProductStateContract

const (
	NotPublished	ProductStateContract	= original.NotPublished
	Published	ProductStateContract	= original.Published
)

type ReportsAggregation = original.ReportsAggregation

const (
	ByAPI		ReportsAggregation	= original.ByAPI
	ByGeo		ReportsAggregation	= original.ByGeo
	ByOperation	ReportsAggregation	= original.ByOperation
	ByProduct	ReportsAggregation	= original.ByProduct
	BySubscription	ReportsAggregation	= original.BySubscription
	ByTime		ReportsAggregation	= original.ByTime
	ByUser		ReportsAggregation	= original.ByUser
)

type SubscriptionStateContract = original.SubscriptionStateContract

const (
	Active		SubscriptionStateContract	= original.Active
	Cancelled	SubscriptionStateContract	= original.Cancelled
	Expired		SubscriptionStateContract	= original.Expired
	Rejected	SubscriptionStateContract	= original.Rejected
	Submitted	SubscriptionStateContract	= original.Submitted
	Suspended	SubscriptionStateContract	= original.Suspended
)

type UserStateContract = original.UserStateContract

const (
	UserStateContractActive		UserStateContract	= original.UserStateContractActive
	UserStateContractBlocked	UserStateContract	= original.UserStateContractBlocked
)

type AccessInformationContract = original.AccessInformationContract
type AccessInformationUpdateParameters = original.AccessInformationUpdateParameters
type APICollection = original.APICollection
type APIContract = original.APIContract
type APIExportResult = original.APIExportResult
type AuthenticationSettingsContract = original.AuthenticationSettingsContract
type AuthorizationServerCollection = original.AuthorizationServerCollection
type BackendCollection = original.BackendCollection
type BackendContract = original.BackendContract
type BackendResponse = original.BackendResponse
type BackendUpdateParameters = original.BackendUpdateParameters
type CertificateCollection = original.CertificateCollection
type CertificateContract = original.CertificateContract
type CertificateCreateOrUpdateParameters = original.CertificateCreateOrUpdateParameters
type DeployConfigurationParameters = original.DeployConfigurationParameters
type ErrorBodyContract = original.ErrorBodyContract
type ErrorFieldContract = original.ErrorFieldContract
type GenerateSsoURLResult = original.GenerateSsoURLResult
type GroupCollection = original.GroupCollection
type GroupContract = original.GroupContract
type GroupCreateParameters = original.GroupCreateParameters
type GroupUpdateParameters = original.GroupUpdateParameters
type IdentityProviderContract = original.IdentityProviderContract
type IdentityProviderList = original.IdentityProviderList
type IdentityProviderUpdateParameters = original.IdentityProviderUpdateParameters
type ListPolicySnippetContract = original.ListPolicySnippetContract
type ListUserIdentityContract = original.ListUserIdentityContract
type LoggerCollection = original.LoggerCollection
type LoggerCreateParameters = original.LoggerCreateParameters
type LoggerResponse = original.LoggerResponse
type LoggerUpdateParameters = original.LoggerUpdateParameters
type OAuth2AuthenticationSettingsContract = original.OAuth2AuthenticationSettingsContract
type OAuth2AuthorizationServerContract = original.OAuth2AuthorizationServerContract
type OAuth2AuthorizationServerUpdateContract = original.OAuth2AuthorizationServerUpdateContract
type OpenIDConnectProviderCollection = original.OpenIDConnectProviderCollection
type OpenidConnectProviderContract = original.OpenidConnectProviderContract
type OpenidConnectProviderCreateContract = original.OpenidConnectProviderCreateContract
type OpenidConnectProviderUpdateContract = original.OpenidConnectProviderUpdateContract
type OperationCollection = original.OperationCollection
type OperationContract = original.OperationContract
type OperationResultContract = original.OperationResultContract
type ParameterContract = original.ParameterContract
type PatchParameters = original.PatchParameters
type PolicySnippetContract = original.PolicySnippetContract
type ProductCollection = original.ProductCollection
type ProductContract = original.ProductContract
type ProductUpdateParameters = original.ProductUpdateParameters
type PropertyCollection = original.PropertyCollection
type PropertyContract = original.PropertyContract
type PropertyCreateParameters = original.PropertyCreateParameters
type PropertyUpdateParameters = original.PropertyUpdateParameters
type QuotaCounterCollection = original.QuotaCounterCollection
type QuotaCounterContract = original.QuotaCounterContract
type QuotaCounterValueContract = original.QuotaCounterValueContract
type RegionContract = original.RegionContract
type RegionListResult = original.RegionListResult
type ReportCollection = original.ReportCollection
type ReportRecordContract = original.ReportRecordContract
type RepresentationContract = original.RepresentationContract
type RequestContract = original.RequestContract
type ResultContract = original.ResultContract
type SaveConfigurationParameter = original.SaveConfigurationParameter
type SubscriptionCollection = original.SubscriptionCollection
type SubscriptionContract = original.SubscriptionContract
type SubscriptionCreateParameters = original.SubscriptionCreateParameters
type SubscriptionKeyParameterNamesContract = original.SubscriptionKeyParameterNamesContract
type SubscriptionUpdateParameters = original.SubscriptionUpdateParameters
type TenantConfigurationSyncStateContract = original.TenantConfigurationSyncStateContract
type TenantLongRunningOperationResult = original.TenantLongRunningOperationResult
type TokenBodyParameterContract = original.TokenBodyParameterContract
type UserCollection = original.UserCollection
type UserContract = original.UserContract
type UserCreateParameters = original.UserCreateParameters
type UserIdentityContract = original.UserIdentityContract
type UserUpdateParameters = original.UserUpdateParameters
type RegionsClient = original.RegionsClient
type TenantConfigurationClient = original.TenantConfigurationClient
type PolicySnippetsClient = original.PolicySnippetsClient
type PropertyClient = original.PropertyClient
type ReportsClient = original.ReportsClient
type APIProductsClient = original.APIProductsClient
type GroupUsersClient = original.GroupUsersClient
type TenantAccessGitClient = original.TenantAccessGitClient
type UserSubscriptionsClient = original.UserSubscriptionsClient
type ProductGroupsClient = original.ProductGroupsClient
type ApisClient = original.ApisClient
type BackendsClient = original.BackendsClient
type CertificatesClient = original.CertificatesClient

const (
	DefaultBaseURI = original.DefaultBaseURI
)

type ManagementClient = original.ManagementClient
type OpenIDConnectProvidersClient = original.OpenIDConnectProvidersClient
type AuthorizationServersClient = original.AuthorizationServersClient

func NewProductSubscriptionsClient(subscriptionID string) ProductSubscriptionsClient {
	return original.NewProductSubscriptionsClient(subscriptionID)
}
func NewProductSubscriptionsClientWithBaseURI(baseURI string, subscriptionID string) ProductSubscriptionsClient {
	return original.NewProductSubscriptionsClientWithBaseURI(baseURI, subscriptionID)
}
func NewQuotaByCounterKeysClient(subscriptionID string) QuotaByCounterKeysClient {
	return original.NewQuotaByCounterKeysClient(subscriptionID)
}
func NewQuotaByCounterKeysClientWithBaseURI(baseURI string, subscriptionID string) QuotaByCounterKeysClient {
	return original.NewQuotaByCounterKeysClientWithBaseURI(baseURI, subscriptionID)
}
func NewUsersClient(subscriptionID string) UsersClient {
	return original.NewUsersClient(subscriptionID)
}
func NewUsersClientWithBaseURI(baseURI string, subscriptionID string) UsersClient {
	return original.NewUsersClientWithBaseURI(baseURI, subscriptionID)
}
func NewIdentityProvidersClient(subscriptionID string) IdentityProvidersClient {
	return original.NewIdentityProvidersClient(subscriptionID)
}
func NewIdentityProvidersClientWithBaseURI(baseURI string, subscriptionID string) IdentityProvidersClient {
	return original.NewIdentityProvidersClientWithBaseURI(baseURI, subscriptionID)
}
func NewLoggersClient(subscriptionID string) LoggersClient {
	return original.NewLoggersClient(subscriptionID)
}
func NewLoggersClientWithBaseURI(baseURI string, subscriptionID string) LoggersClient {
	return original.NewLoggersClientWithBaseURI(baseURI, subscriptionID)
}
func NewProductApisClient(subscriptionID string) ProductApisClient {
	return original.NewProductApisClient(subscriptionID)
}
func NewProductApisClientWithBaseURI(baseURI string, subscriptionID string) ProductApisClient {
	return original.NewProductApisClientWithBaseURI(baseURI, subscriptionID)
}
func NewGroupsClient(subscriptionID string) GroupsClient {
	return original.NewGroupsClient(subscriptionID)
}
func NewGroupsClientWithBaseURI(baseURI string, subscriptionID string) GroupsClient {
	return original.NewGroupsClientWithBaseURI(baseURI, subscriptionID)
}
func NewUserIdentitiesClient(subscriptionID string) UserIdentitiesClient {
	return original.NewUserIdentitiesClient(subscriptionID)
}
func NewUserIdentitiesClientWithBaseURI(baseURI string, subscriptionID string) UserIdentitiesClient {
	return original.NewUserIdentitiesClientWithBaseURI(baseURI, subscriptionID)
}
func NewSubscriptionsClient(subscriptionID string) SubscriptionsClient {
	return original.NewSubscriptionsClient(subscriptionID)
}
func NewSubscriptionsClientWithBaseURI(baseURI string, subscriptionID string) SubscriptionsClient {
	return original.NewSubscriptionsClientWithBaseURI(baseURI, subscriptionID)
}
func NewTenantAccessClient(subscriptionID string) TenantAccessClient {
	return original.NewTenantAccessClient(subscriptionID)
}
func NewTenantAccessClientWithBaseURI(baseURI string, subscriptionID string) TenantAccessClient {
	return original.NewTenantAccessClientWithBaseURI(baseURI, subscriptionID)
}
func NewTenantConfigurationSyncStateClient(subscriptionID string) TenantConfigurationSyncStateClient {
	return original.NewTenantConfigurationSyncStateClient(subscriptionID)
}
func NewTenantConfigurationSyncStateClientWithBaseURI(baseURI string, subscriptionID string) TenantConfigurationSyncStateClient {
	return original.NewTenantConfigurationSyncStateClientWithBaseURI(baseURI, subscriptionID)
}
func NewUserGroupsClient(subscriptionID string) UserGroupsClient {
	return original.NewUserGroupsClient(subscriptionID)
}
func NewUserGroupsClientWithBaseURI(baseURI string, subscriptionID string) UserGroupsClient {
	return original.NewUserGroupsClientWithBaseURI(baseURI, subscriptionID)
}
func UserAgent() string {
	return original.UserAgent()
}
func Version() string {
	return original.Version()
}
func NewAPIOperationsClient(subscriptionID string) APIOperationsClient {
	return original.NewAPIOperationsClient(subscriptionID)
}
func NewAPIOperationsClientWithBaseURI(baseURI string, subscriptionID string) APIOperationsClient {
	return original.NewAPIOperationsClientWithBaseURI(baseURI, subscriptionID)
}
func NewProductsClient(subscriptionID string) ProductsClient {
	return original.NewProductsClient(subscriptionID)
}
func NewProductsClientWithBaseURI(baseURI string, subscriptionID string) ProductsClient {
	return original.NewProductsClientWithBaseURI(baseURI, subscriptionID)
}
func NewQuotaByPeriodKeysClient(subscriptionID string) QuotaByPeriodKeysClient {
	return original.NewQuotaByPeriodKeysClient(subscriptionID)
}
func NewQuotaByPeriodKeysClientWithBaseURI(baseURI string, subscriptionID string) QuotaByPeriodKeysClient {
	return original.NewQuotaByPeriodKeysClientWithBaseURI(baseURI, subscriptionID)
}
func NewRegionsClient(subscriptionID string) RegionsClient {
	return original.NewRegionsClient(subscriptionID)
}
func NewRegionsClientWithBaseURI(baseURI string, subscriptionID string) RegionsClient {
	return original.NewRegionsClientWithBaseURI(baseURI, subscriptionID)
}
func NewTenantConfigurationClient(subscriptionID string) TenantConfigurationClient {
	return original.NewTenantConfigurationClient(subscriptionID)
}
func NewTenantConfigurationClientWithBaseURI(baseURI string, subscriptionID string) TenantConfigurationClient {
	return original.NewTenantConfigurationClientWithBaseURI(baseURI, subscriptionID)
}
func NewPolicySnippetsClient(subscriptionID string) PolicySnippetsClient {
	return original.NewPolicySnippetsClient(subscriptionID)
}
func NewPolicySnippetsClientWithBaseURI(baseURI string, subscriptionID string) PolicySnippetsClient {
	return original.NewPolicySnippetsClientWithBaseURI(baseURI, subscriptionID)
}
func NewPropertyClient(subscriptionID string) PropertyClient {
	return original.NewPropertyClient(subscriptionID)
}
func NewPropertyClientWithBaseURI(baseURI string, subscriptionID string) PropertyClient {
	return original.NewPropertyClientWithBaseURI(baseURI, subscriptionID)
}
func NewReportsClient(subscriptionID string) ReportsClient {
	return original.NewReportsClient(subscriptionID)
}
func NewReportsClientWithBaseURI(baseURI string, subscriptionID string) ReportsClient {
	return original.NewReportsClientWithBaseURI(baseURI, subscriptionID)
}
func NewUserSubscriptionsClient(subscriptionID string) UserSubscriptionsClient {
	return original.NewUserSubscriptionsClient(subscriptionID)
}
func NewUserSubscriptionsClientWithBaseURI(baseURI string, subscriptionID string) UserSubscriptionsClient {
	return original.NewUserSubscriptionsClientWithBaseURI(baseURI, subscriptionID)
}
func NewAPIProductsClient(subscriptionID string) APIProductsClient {
	return original.NewAPIProductsClient(subscriptionID)
}
func NewAPIProductsClientWithBaseURI(baseURI string, subscriptionID string) APIProductsClient {
	return original.NewAPIProductsClientWithBaseURI(baseURI, subscriptionID)
}
func NewGroupUsersClient(subscriptionID string) GroupUsersClient {
	return original.NewGroupUsersClient(subscriptionID)
}
func NewGroupUsersClientWithBaseURI(baseURI string, subscriptionID string) GroupUsersClient {
	return original.NewGroupUsersClientWithBaseURI(baseURI, subscriptionID)
}
func NewTenantAccessGitClient(subscriptionID string) TenantAccessGitClient {
	return original.NewTenantAccessGitClient(subscriptionID)
}
func NewTenantAccessGitClientWithBaseURI(baseURI string, subscriptionID string) TenantAccessGitClient {
	return original.NewTenantAccessGitClientWithBaseURI(baseURI, subscriptionID)
}
func New(subscriptionID string) ManagementClient {
	return original.New(subscriptionID)
}
func NewWithBaseURI(baseURI string, subscriptionID string) ManagementClient {
	return original.NewWithBaseURI(baseURI, subscriptionID)
}
func NewOpenIDConnectProvidersClient(subscriptionID string) OpenIDConnectProvidersClient {
	return original.NewOpenIDConnectProvidersClient(subscriptionID)
}
func NewOpenIDConnectProvidersClientWithBaseURI(baseURI string, subscriptionID string) OpenIDConnectProvidersClient {
	return original.NewOpenIDConnectProvidersClientWithBaseURI(baseURI, subscriptionID)
}
func NewProductGroupsClient(subscriptionID string) ProductGroupsClient {
	return original.NewProductGroupsClient(subscriptionID)
}
func NewProductGroupsClientWithBaseURI(baseURI string, subscriptionID string) ProductGroupsClient {
	return original.NewProductGroupsClientWithBaseURI(baseURI, subscriptionID)
}
func NewApisClient(subscriptionID string) ApisClient {
	return original.NewApisClient(subscriptionID)
}
func NewApisClientWithBaseURI(baseURI string, subscriptionID string) ApisClient {
	return original.NewApisClientWithBaseURI(baseURI, subscriptionID)
}
func NewBackendsClient(subscriptionID string) BackendsClient {
	return original.NewBackendsClient(subscriptionID)
}
func NewBackendsClientWithBaseURI(baseURI string, subscriptionID string) BackendsClient {
	return original.NewBackendsClientWithBaseURI(baseURI, subscriptionID)
}
func NewCertificatesClient(subscriptionID string) CertificatesClient {
	return original.NewCertificatesClient(subscriptionID)
}
func NewCertificatesClientWithBaseURI(baseURI string, subscriptionID string) CertificatesClient {
	return original.NewCertificatesClientWithBaseURI(baseURI, subscriptionID)
}
func NewAuthorizationServersClient(subscriptionID string) AuthorizationServersClient {
	return original.NewAuthorizationServersClient(subscriptionID)
}
func NewAuthorizationServersClientWithBaseURI(baseURI string, subscriptionID string) AuthorizationServersClient {
	return original.NewAuthorizationServersClientWithBaseURI(baseURI, subscriptionID)
}
